# Generated by Django 4.0.4 on 2022-05-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teahouse', '0002_preperation_temperature_alter_tea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preperation',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
