# Generated by Django 4.0.4 on 2022-05-04 12:52

from django.db import migrations, models
import teahouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('teahouse', '0003_alter_preperation_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[(teahouse.models.TeaCategory['GREEN'], 'Green'), (teahouse.models.TeaCategory['BLACK'], 'Black'), (teahouse.models.TeaCategory['OOLONG'], 'Oolong'), (teahouse.models.TeaCategory['SHENG_PUER'], "Sheng Pu'er"), (teahouse.models.TeaCategory['SHU_PUER'], "Shu Pu'er"), (teahouse.models.TeaCategory['WHITE'], 'White'), (teahouse.models.TeaCategory['AGED_WHITE'], 'Aged White')], max_length=20),
        ),
    ]
