# Generated by Django 4.0.4 on 2022-05-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teahouse', '0004_alter_tea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[('GREEN', 'Green'), ('BLACK', 'Black'), ('OOLONG', 'Oolong'), ('SHENG_PUER', "Sheng Pu'er"), ('SHU_PUER', "Shu Pu'er"), ('WHITE', 'White'), ('AGED_WHITE', 'Aged White')], max_length=20),
        ),
    ]
