# Generated by Django 4.0.4 on 2022-05-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teahouse', '0005_alter_tea_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='preperation',
            new_name='preperations',
        ),
    ]
