# Generated by Django 4.0.4 on 2022-05-04 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teahouse', '0006_rename_preperation_tea_preperations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='preperations',
            new_name='preperation',
        ),
    ]
