# Generated by Django 4.0.4 on 2022-05-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teahouse', '0007_rename_preperations_tea_preperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tea',
            old_name='preperation',
            new_name='preperations',
        ),
    ]
